### PR TITLE
Update README.md to add more details on dependencies and running tests

### PR DESCRIPTION
**Pull request by mohataher**

### CODE REVIEW

**Comment by mohataher** [comment]
The scripts installs OpenCV and all dependencies that might be required to run any of its routines. Is it too much for your library?

**Comment by severin-lemaignan** [comment]
Sorry, my question was: why not simply `sudo apt-get install libopencv-dev`?

**Comment by mohataher** [comment]
I prefer to do a full installation to all other libraries that OpenCV might require. If you're sure that this is all your library needs, then I will change it.

**Comment by severin-lemaignan** [comment]
Well, `apt` will take care of installing all OpenCV dependencies!

**Comment by severin-lemaignan** [comment]
Merged, thanks!

**Pull request merged**
